CREATE OR REPLACE VIEW VIEW_SIM_PLAN_PACKAGE AS 
SELECT  
    SIM.SIM_ID,  
    MP.PLAN_ID,  
    SP.SERVICE_PACKAGE_ID 
FROM  
    SIM_CARD SIM
JOIN  
    SIMCARD_MOBILEPLAN SMP 
    ON SIM.SIM_ID = SMP.SIM_ID 
JOIN  
    MOBILEPLAN MP 
    ON SMP.PLAN_ID = MP.PLAN_ID 
JOIN  
    SERVICEPACKAGE_MOBILEPLAN SPMP 
    ON MP.PLAN_ID = SPMP.PLAN_ID 
JOIN  
    SERVICEPACKAGE SP 
    ON SPMP.SERVICE_PACKAGE_ID = SP.SERVICE_PACKAGE_ID 
WHERE  
    EXISTS (
        SELECT 1 
        FROM CAMPAIGN C 
        WHERE C.CAMPAIGN_STATUS = 'Active'
    );
SELECT * FROM VIEW_SIM_PLAN_PACKAGE;